# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: echo Hello, world!

    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
      name: Heroku Deploy with Telegram
	'on': 
		push:
			branches: [master]
jobs:
	build:
		runs-on: ubuntu-latest
		steps:
			- name: Checkout
			  uses: actions/checkout@v2

			- name: Deploy to Heroku
			  uses: Suvink/heroku-static@v0.3
			  with:
				heroku_app_name: Your unique Heroku app name
				heroku_email: Email you used for Heroku
				dontuseforce: false #Disable force push [optional]
				buildpack: Your buildpack 
			  env:
				HEROKU_TOKEN: '${{ secrets.HEROKU_TOKEN }}'
				BOT_TOKEN: '${{ secrets.BOT_TOKEN }}'
				CHAT_ID: '${{ secrets.CHAT_ID }}'  echo test, and deploy your project.
